name: 'Datarepo GitHub Actions'
description: 'Runs various commands via GitHub Actions.'
branding:
  icon: 'terminal'
  color: 'purple'
inputs:
  actions_subcommand:
    description: 'Terraform subcommand to execute.'
    required: true
  ct_actions_version:
    description: 'consul-template version to install.'
    required: true
  role_id:
    description: 'role_id for vault'
  secret_id:
    description: 'secret_id for vault'
  tf_actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
  actions_working_dir:
    description: 'working directory.'
    default: '.'
outputs:
  tf_actions_output:
    description: 'The Terraform outputs in JSON format.'
  tf_actions_plan_has_changes:
    description: 'Whether or not the Terraform plan contained changes.'
  tf_actions_plan_output:
    description: 'The Terraform plan output.'
runs:
  using: 'docker'
  image: './Dockerfile'
