name: 'Datarepo GitHub Actions'
description: 'Runs various commands via GitHub Actions.'
branding:
  icon: 'terminal'
  color: 'purple'
inputs:
  actions_subcommand:
    description: 'Terraform subcommand to execute.'
    required: true
  role_id:
    description: 'role_id for vault'
  secret_id:
    description: 'secret_id for vault'
  vault_address:
    description: 'https address for vault'
    default: 'https://clotho.broadinstitute.org:8200'
  google_zone:
    description: 'Google zone for sdk ie:us-central1'
    default: 'us-central1'
  google_project:
    description: 'Google project for sdk ie:broad-jade-integration'
    default: 'broad-jade-integration'
  gcr_google_project:
    description: 'Google project for GCR image ie:broad-jade-dev'
    default: 'broad-jade-dev'
  k8_cluster:
    description: 'Google kubernetes cluster for sdk ie:integration-master'
    default: 'integration-master'
  k8_namespaces:
    description: 'Google kubernetes cluster namespaces ie:"integration-1" "integration-2"'
  helm_secret_chart_version:
    description: 'Helm chart version for datarepo-helm/create-secret-manager-secret ie:0.0.4'
  helm_datarepo_chart_version:
    description: 'Helm chart version for datarepo-helm/datarepo ie:0.0.8'
  gcr_tag:
    description: 'gcr_tag of the docker image to deploy'
  actions_working_dir:
    description: 'working directory.'
    default: '.'
runs:
  using: 'docker'
  image: './Dockerfile'
